# cloud-init.yaml
#cloud-config
packages:
  - snapd

runcmd:
  - snap install microk8s --classic
  - usermod -a -G microk8s ubuntu
  - microk8s status --wait-ready
  - microk8s enable dns storage cert-manager observability metrics-server prometheus
