# monitoring-cluster.yml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: monitoring-poc
  namespace: elastic-system
spec:
  version: 8.16.1
  nodeSets:
    - name: monitoring-data
      count: 1
      config:
        node.roles: ["master", "data", "remote_cluster_client"] # Pas besoin "ingest" ici car: Aucun prétraitement de données+Les données de monitoring sont automatiquement indexées par Elasticsearch.
        node.store.allow_mmap: false
        #xpack.monitoring.enabled: true
        # Configuration pour l'élection des master nodes
        ##discovery.zen.minimum_master_nodes: 2  # Pour 3 nœuds (quorum = (N/2)+1)
        ##cluster.initial_master_nodes:
        ##  - monitoring-poc-es-monitoring-nodes-0
        ##  - monitoring-poc-es-monitoring-nodes-1
        ##  - monitoring-poc-es-monitoring-nodes-2
      podTemplate:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: monitoring-node
                        operator: In
                        values: ["yes"]
            #podAntiAffinity: # éviter 2 master-data sur le même hôte :contentReference[oaicite:1]{index=1}
            #  requiredDuringSchedulingIgnoredDuringExecution:
#  - labelSelector:
#                   matchLabels:
#                    elasticsearch.k8s.elastic.co/node-master: "true"
#topologyKey: "kubernetes.io/hostname"
#containers:
#  - name: elasticsearch
#              resources:
#  requests:
#    memory: "2Gi"
#    cpu: "1"
#  limits:
#    memory: "3Gi"
